// Mock check-in data for testing ArcTimeline component
// Copy this into your test file or component

export const mockCheckIns = [
  {
    id: "1",
    journeyId: "journey-1",
    date: "2024-12-01",
    accomplishment: "Started the project by setting up the Next.js application with TypeScript and Tailwind CSS. Created the initial folder structure and configured the development environment.",
    notes: "Had some issues with Tailwind configuration but resolved it by checking the official docs.",
    wordCount: 156,
    promptUsed: "What did you build today?",
    githubCommits: null,
    commitCount: 5,
    createdAt: new Date("2024-12-01T10:30:00"),
    editedAt: null,
  },
  {
    id: "2",
    journeyId: "journey-1",
    date: "2024-12-02",
    accomplishment: "Implemented user authentication using NextAuth.js with Google OAuth. Set up the database schema for users and sessions. Created protected routes and middleware for authentication.",
    notes: null,
    wordCount: 198,
    promptUsed: "What did you accomplish?",
    githubCommits: null,
    commitCount: 8,
    createdAt: new Date("2024-12-02T14:20:00"),
    editedAt: null,
  },
  {
    id: "3",
    journeyId: "journey-1",
    date: "2024-12-03",
    accomplishment: "Built the journey creation form with proper validation using Zod. Users can now create journeys with title, description, tech stack, and target check-ins. Added the journey card component to display all user journeys.",
    notes: "Need to add edit functionality tomorrow. Also considering adding journey templates for common project types.",
    wordCount: 245,
    promptUsed: "What progress did you make?",
    githubCommits: null,
    commitCount: 12,
    createdAt: new Date("2024-12-03T16:45:00"),
    editedAt: new Date("2024-12-03T18:30:00"),
  },
  {
    id: "4",
    journeyId: "journey-1",
    date: "2024-12-05",
    accomplishment: "Implemented the daily check-in system. Users can now log their daily progress with accomplishments, notes, and word count. Added streak tracking logic and XP calculation. Created a beautiful calendar grid to visualize check-ins.",
    notes: null,
    wordCount: 301,
    promptUsed: "What did you ship today?",
    githubCommits: null,
    commitCount: 15,
    createdAt: new Date("2024-12-05T11:15:00"),
    editedAt: null,
  },
  {
    id: "5",
    journeyId: "journey-1",
    date: "2024-12-06",
    accomplishment: "Added GitHub integration to automatically fetch commits. Set up webhook handling and OAuth flow for GitHub. Now commits are automatically tracked with each check-in!",
    notes: "GitHub API was a bit tricky with rate limits. Implemented caching to avoid hitting limits.",
    wordCount: 178,
    promptUsed: "What did you build?",
    githubCommits: null,
    commitCount: 0,
    createdAt: new Date("2024-12-06T15:00:00"),
    editedAt: null,
  },
  {
    id: "6",
    journeyId: "journey-1",
    date: "2024-12-07",
    accomplishment: "Worked on the journey status system - implemented frozen and dead states based on inactivity. Added warning notifications when users are about to lose their streak. Created a cron job to automatically update journey statuses.",
    notes: null,
    wordCount: 267,
    promptUsed: "What did you accomplish today?",
    githubCommits: null,
    commitCount: 9,
    createdAt: new Date("2024-12-07T13:30:00"),
    editedAt: null,
  },
  {
    id: "7",
    journeyId: "journey-1",
    date: "2024-12-09",
    accomplishment: "Built the Arc celebration modal! When users complete their target check-ins, they get a beautiful confetti animation and transition to Arc phase. Added the ability to extend journeys or mark them as complete.",
    notes: "The confetti effect looks amazing! Users are going to love this feature.",
    wordCount: 289,
    promptUsed: "What did you create?",
    githubCommits: null,
    commitCount: 18,
    createdAt: new Date("2024-12-09T17:00:00"),
    editedAt: null,
  },
  {
    id: "8",
    journeyId: "journey-1",
    date: "2024-12-10",
    accomplishment: "Created the Arc showcase page for completed journeys. Added beautiful stats visualizations, timeline view, and daily progress grid. Implemented sharing functionality with Twitter and LinkedIn integration.",
    notes: "Still need to add PDF export and OG image generation. Will work on that next week.",
    wordCount: 312,
    promptUsed: "What did you ship?",
    githubCommits: null,
    commitCount: 22,
    createdAt: new Date("2024-12-10T19:45:00"),
    editedAt: null,
  },
]

// Shorter array for quick testing (just 3 check-ins)
export const mockCheckInsShort = [
  {
    id: "1",
    journeyId: "journey-1",
    date: "2024-12-20",
    accomplishment: "Started building the MonkArc landing page. Created hero section with gradient backgrounds and animated elements.",
    notes: "Need to work on mobile responsiveness tomorrow.",
    wordCount: 123,
    promptUsed: "What did you build today?",
    githubCommits: null,
    commitCount: 7,
    createdAt: new Date("2024-12-20T10:00:00"),
    editedAt: null,
  },
  {
    id: "2",
    journeyId: "journey-1",
    date: "2024-12-21",
    accomplishment: "Finished the features section and pricing page. Added share buttons and improved the overall design consistency.",
    notes: null,
    wordCount: 145,
    promptUsed: "What progress did you make?",
    githubCommits: null,
    commitCount: 12,
    createdAt: new Date("2024-12-21T14:30:00"),
    editedAt: null,
  },
  {
    id: "3",
    journeyId: "journey-1",
    date: "2024-12-22",
    accomplishment: "Deployed to production! Fixed all the bugs and performance issues. The landing page is now live and looking amazing.",
    notes: "Celebration time! 🎉",
    wordCount: 167,
    promptUsed: "What did you accomplish?",
    githubCommits: null,
    commitCount: 5,
    createdAt: new Date("2024-12-22T18:00:00"),
    editedAt: new Date("2024-12-22T18:30:00"),
  },
]